CREATE TABLE train_interchange (
    id INT NOT NULL AUTO_INCREMENT,
    departure_number VARCHAR(5) NOT NULL,
    arrival_number VARCHAR(5) NOT NULL,
    departure_station VARCHAR(64) NOT NULL,
    transfer_station VARCHAR(64) NOT NULL,
    arrival_station VARCHAR(64) NOT NULL,
    departure_from_date VARCHAR(32) NOT NULL,
    departure_to_date VARCHAR(32) NOT NULL,
    arrival_from_date VARCHAR(32) NOT NULL,
    arrival_to_date VARCHAR(32) NOT NULL,
    departure_from_time VARCHAR(8) NOT NULL,
    departure_to_time VARCHAR(8) NOT NULL,
    interchange_duration VARCHAR(5) NOT NULL,
    arrival_from_time VARCHAR(8) NOT NULL,
    arrival_to_time VARCHAR(8) NOT NULL,
    travel_time VARCHAR(5) NOT NULL,
    process_date DATE NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (
      departure_number,
      arrival_number,
      departure_station,
      transfer_station,
      arrival_station,
      departure_from_date,
      departure_to_date,
      arrival_from_date,
      arrival_to_date,
      departure_from_time,
      departure_to_time,
      interchange_duration,
      arrival_from_time,
      arrival_to_time,
      travel_time,
      process_date
    )
);
